# Generated by Django 6.0.6 on 2026-07-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Programming Languages', 'Programming Languages'), ('Web Development', 'Web Development'), ('Database', 'Database'), ('Computer Science Skills', 'Computer Science Skills'), ('Tools', 'Tools')], max_length=50)),
                ('skill_name', models.CharField(max_length=100)),
            ],
        ),
    ]
